//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Playmobil
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaga
    {
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public Nullable<decimal> Remuneracao { get; set; }
        public int Id { get; set; }
        public Nullable<System.DateTime> DataExpiracao { get; set; }
    }
}
